version: '3.7'

services:

  ui-node:
    container_name: ui-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=http://localhost
      - VUE_APP_API_URL_KEYCLOAK=http://keycloak:8080/auth/realms


networks:
  default:
    external:
      name: task_management
