version: '3.7'

services:

  ui-node:
    container_name: ui-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
